### ISSUE TITLE
Repeat Daily Notification?

### ISSUE THREAD

**Issue by Madi99** [jakebonk/NotifyMe#4]
how to make repeat daily notification?

**Comment by jakebonk** [comment]
Thats actually not implemented in this current version but I do have it done in the newer version. I should be able to push it today. The new system works by setting an rrule string. Here's an interactive way to visualize rrule: https://jakubroztocil.github.io/rrule/

just adding
.rrule("FREQ=DAILY")
to your NotifyMe Builder should do the trick.
